# Generated by Django 3.1.4 on 2020-12-27 14:01

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='enquarydata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('courses', multiselectfield.db.fields.MultiSelectField(choices=[('python', 'python'), ('django', 'django'), ('ui', 'ui'), ('restapi', 'restapi')], max_length=200)),
                ('trainers', multiselectfield.db.fields.MultiSelectField(choices=[('mani', 'mani'), ('guru', 'guru'), ('chinna', 'chinna')], max_length=200)),
                ('locations', multiselectfield.db.fields.MultiSelectField(choices=[('hyd', 'hyd'), ('bangalore', 'bangalore'), ('chennai', 'chennai'), ('delhi', 'delhi')], max_length=200)),
                ('gender', models.CharField(max_length=100)),
                ('start_date', models.DateField(max_length=100)),
            ],
        ),
    ]
